# Generated by Django 6.0 on 2025-12-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(choices=[('oidc', 'OIDC'), ('saml', 'SAML'), ('system', 'SYSTEM')], default='system', max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('outcome', models.CharField(default='INFO', max_length=30)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
